#!/bin/bash
clear
rm -f ./output/*.zip
rm -rf ./output/boot
rm -rf ./output/system/lib/modules
mkdir -p ./output/system/lib/modules
mkdir -p ./output/boot
#./mkbootfs ./ramdisk | gzip > ramdisk.gz
cp ramdisk.cpio.gz ./output/boot
cd HW01EKERNEL
export CROSS_COMPILE="../ccache ../android-toolchain-eabi/bin/arm-linux-androideabi-"
export ARCH=arm
make clean -j4
make -j16
cd ../
cp ./mkbootimg ./output/boot
find . -name '*.ko' -exec cp {} ./output/system/lib/modules  \;
find . -name 'zImage' -exec cp {} ./output/boot  \;
cd ./output/boot
base=0x80200000
kerneloff=0x00008000
ramoff=0x01400000
tagsoff=0x00000100
cmd_line="androidboot.hardware=huawei user_debug=31 kgsl.mmutype=gpummu"
./mkbootimg --kernel ./zImage --ramdisk ./ramdisk.cpio.gz --cmdline "$cmd_line" --base $base --kernel_offset $kerneloff --ramdisk_offset $ramoff --tags_offset $tagsoff --pagesize 2048 -o boot.img
mv ./boot.img ../boot.img
cd ../
rm -rf ./boot/
zip -r HW01ENinjaKernel.zip *
rm -f ./boot.
